---
title: "Figure2_imputation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(imputeLCMD)
library(pcaMethods)
library(missForest)
library(ComplexHeatmap)
set.seed(4242)
library(hydroGOF)
library(ggcorrplot)
library(corrplot)
library(circlize)
library(RColorBrewer)
library(viridis)
library(readxl)
```

# Figure 2.A
```{r}
fragment_comb <- read.table("foldchnge_fragment_9_unnorm.txt", sep = "\t", stringsAsFactors = FALSE)

colnames(fragment_comb) <-as.data.frame(fragment_comb[1,])

fragment_comb <- as.data.frame(fragment_comb[-1,])

fragment_comb <- filter(fragment_comb, !imputation == "imputation")

fragment_comb[, 3] <- lapply(3, function(x) as.numeric(fragment_comb[[x]]))

fragment_comb$imputation[grep("no_imp", fragment_comb$imputation)] <- "None"
fragment_comb$imputation[grep("zero_imp", fragment_comb$imputation)] <- "Zero"
fragment_comb$imputation[grep("minDet_imp", fragment_comb$imputation)] <- "minDet"
fragment_comb$imputation[grep("minProb_imp", fragment_comb$imputation)] <- "minProb"
fragment_comb$imputation[grep("svd_imp", fragment_comb$imputation)] <- "SVDmethod"
fragment_comb$imputation[grep("bpca_imp", fragment_comb$imputation)] <- "BPCA"
fragment_comb$imputation[grep("knn_imp", fragment_comb$imputation)] <- "KNNmethod"
fragment_comb$imputation[grep("lls_imp", fragment_comb$imputation)] <- "LLS"
fragment_comb$imputation[grep("rf_imp", fragment_comb$imputation)] <- "Random Forest"


fragment_comb$imputation <- factor(fragment_comb$imputation, levels = unique(fragment_comb$imputation), ordered = TRUE)

imp_methods_col <- c('#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#ffff33','#a65628','#f781bf','#999999')

ggplot(fragment_comb, aes(x = load, y = foldchange, fill = imputation)) +
  geom_boxplot() +
  theme_bw() +
  theme(text = element_text(size = 35)) +
  scale_y_continuous(breaks=seq(-14, 15, 1)) +
  geom_hline(yintercept = 2) +
  geom_hline(yintercept = 1) +
  scale_fill_manual(values = imp_methods_col) +
  labs(y = "Fold Change", x = "Sample Concentration")
```

# Figure 2.B
```{r}
comb_imp_foldchnge <- read.csv("comb_imp_foldchnge.csv")

comb_imp_foldchnge <- as.data.frame(comb_imp_foldchnge[,-1])

colnames(comb_imp_foldchnge) <- c("Random Forest", "LLS", "KNNmethod",
                                  "BPCA", "SVDmethod", "minProb", "minDet",
                                  "Zero", "None", "Ideal")

corr_foldchnge_imp <- cor(comb_imp_foldchnge)
p.imp <- cor_pmat(comb_imp_foldchnge)

corr_foldchnge_imp <- as.matrix(corr_foldchnge_imp)


column_ha = HeatmapAnnotation(correlation_coefficient = anno_barplot(corr_foldchnge_imp[c(1:10), 10]),
                              annotation_name_gp= gpar(fontsize = 15))


hmap <- Heatmap(
  corr_foldchnge_imp,
  show_row_names = T,
  show_column_names = T,
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_column_dend = TRUE,
  show_row_dend = TRUE,
  row_dend_reorder = TRUE,
  column_dend_reorder = TRUE,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"),
  heatmap_legend_param = list(
    title = "Pearson's correlation coefficient",
    title_position = "topcenter",
    direction = "horizontal"),
  row_names_gp = gpar(fontsize = 20),
  column_names_gp = gpar(fontsize = 20))

draw(hmap, heatmap_legend_side="bottom")
```


# Figure 2.C
```{r}
rsr_fragment_imp <- read.csv("rsr_fragment_imp.csv", stringsAsFactors = F)
rsr_fragment_imp$imputation <- c("Ideal", "None", "Zero", "minDet", "minProb",
                                 "SVDmethod", "BPCA", "KNNmethod", "LLS","Random Forest")


label_V1 <- rsr_fragment_imp$V1

label_V1 <- round(label_V1, digits = 2)

rsr_fragment_imp$imputation <- factor(rsr_fragment_imp$imputation, 
                                      levels = unique(rsr_fragment_imp$imputation),ordered = TRUE)


ggplot(rsr_fragment_imp, aes(x = imputation, y = V1, fill = imputation)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("black", imp_methods_col)) +
  theme_bw() +
  labs(x = "Imputation Methods", y = "Ratio of RMSE to the standard deviation") +
  geom_text(aes(label=label_V1), position=position_dodge(width=0.9), vjust=-0.25,
            size = 10) +
  theme(text = element_text(size = 35),
        axis.text.x = element_blank(),
        axis.ticks.x=element_blank())
```


