---
title: "Figure6_imputation_paper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# loading libraries
```{r message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(imputeLCMD)
library(pcaMethods)
library(missForest)
library(ComplexHeatmap)
set.seed(4242)
library(hydroGOF)
library(ggcorrplot)
library(corrplot)
library(circlize)
library(RColorBrewer)
library(viridis)
library(readxl)
```

# reading in all the files
```{r message=FALSE}
# ROTS DEPs
# noimp
rots_noimp_prim <- read.csv("rots_prim_noimp.csv", stringsAsFactors = F)

# BPCA all log transformed
rots_bpca_log2_prim <- read.csv("rots_fragm_imp_prim_bpca_k10_log2.csv", stringsAsFactors = F)

# RF all log transformed
rots_rf_log2_prim <- read.csv("rots_fragm_imp_prim_rf_log2.csv", stringsAsFactors = F)

# null DEPs
null_rots_prim <- read.csv("null_rots_prim_noimp2.csv", stringsAsFactors = F)

colnames(rots_noimp_prim) <- c("Protein", "log2FoldChange", "pvalue", "FDR",
                               "col_FDR", "col_pvalue")


colnames(rots_rf_log2_prim) <- colnames(rots_noimp_prim)
colnames(rots_bpca_log2_prim) <- colnames(rots_noimp_prim)
colnames(null_rots_prim) <- colnames(rots_noimp_prim)

# non filtered pocroc data all 103 samples with replicates

pocroc_data <- read.csv("protein_quant_pocroc_103_norm.csv", stringsAsFactors = F)

pocroc_data <- as.data.frame(pocroc_data[-1,-1])

pocroc_data <- separate(pocroc_data, col = Protein, into = c("a", "b", "Protein"), sep = "\\|")

pocroc_data <- subset(pocroc_data, select = -c(a,b))

rownames(pocroc_data) <- NULL

pocroc_data <- column_to_rownames(pocroc_data, "Protein")
#pocroc_data <- column_to_rownames(pocroc_data, "From")

# removing pooled samples

pocroc_data <- as.data.frame(pocroc_data[,-c(grep("pool", colnames(pocroc_data)))])

# coldata for the entire data set

coldata_final <- read.csv("coldata_final_103.csv", stringsAsFactors = F)


coldata_final <- as.data.frame(coldata_final, stringsAsFactors = F)

rownames(coldata_final) <- NULL

coldata_final <- column_to_rownames(coldata_final, "X")
coldata_final$TumorType[grep("Prim", coldata_final$TumorType)] <- "Primary"
coldata_final$TumorType[grep("PRIMAR", coldata_final$TumorType)] <- "Primary"

coldata_final$TumorType[grep("Recurr", coldata_final$TumorType)] <- "Recurrent"
coldata_final$TumorType[grep("RECURR", coldata_final$TumorType)] <- "Recurrent"

coldata_final$TumorType[grep("strm", coldata_final$phase)] <- "Stromal"
coldata_final$TumorType[grep("all", coldata_final$TumorType)] <- "pool"

coldata_final <- as.data.frame(coldata_final[-c(grep("pool", rownames(coldata_final))),])

samples_primary_paired_tum_strm <- read.table("samples_primary_paired_tum_strm.txt",
                                              stringsAsFactors = F)

coldata_final_primary <- filter(coldata_final, rownames(coldata_final) %in% samples_primary_paired_tum_strm$V1)
coldata_final_primary <- rownames_to_column(coldata_final_primary, "sample")
coldata_final_primary[, 8] <- lapply(8, function(x) as.character(coldata_final_primary[[x]]))

pocroc_data_primary <- subset(pocroc_data, select = samples_primary_paired_tum_strm$V1)

pocroc_data_primary <- filter(pocroc_data_primary, rownames(pocroc_data_primary) %in% rots_noimp_prim$Protein)

data_format_prot <- function(data){
  if(sum(is.na(data) > 0)){
    print("Data has missing values")
    df <- na.omit(data)
    df <- as.data.frame(df[-1,-1])
    df <- separate(df, col = Protein, into = c("a", "b", "Protein"), sep = "\\|")
    df <- subset(df, select = -c(a,b))
    rownames(df) <- NULL
    df <- column_to_rownames(df, "Protein")
  } else{
    print("Data has no NA values")
    df <- as.data.frame(data)
    df <- as.data.frame(df[-1,-1])
    df <- separate(df, col = Protein, into = c("a", "b", "Protein"), sep = "\\|")
    df <- subset(df, select = -c(a,b))
    rownames(df) <- NULL
    df <- column_to_rownames(df, "Protein")
  }
   df
}

# BPCA all log transformed
prot_bpca_5k_log2 <- read.csv("protein_quant_fragm_imp_prim_bpca_k10_log2.csv", stringsAsFactors = F)
prot_bpca_5k_log2 <- data_format_prot(prot_bpca_5k_log2)
colnames(prot_bpca_5k_log2) <- colnames(pocroc_data_primary)

# RF all log tranformed
prot_rf_5k_log2 <- read.csv("protein_quant_fragm_imp_prim_rf_log2.csv", stringsAsFactors = F)
prot_rf_5k_log2 <- data_format_prot(prot_rf_5k_log2)
colnames(prot_rf_5k_log2) <- colnames(pocroc_data_primary)
```

# Table 1; correlation of p-values and false postive percent
```{r message=FALSE}
corr_function_pvalue <- function(data){
  #tumor
  df_tumor <- filter(data, log2FoldChange > 0) 
  rots_noimp_tumor <- filter(rots_noimp_prim, log2FoldChange > 0)
  df_tumor <- filter(df_tumor, Protein %in% rots_noimp_tumor$Protein)
  rots_noimp_tumor <- filter(rots_noimp_tumor, Protein %in% df_tumor$Protein)
  
  df_tumor <- df_tumor[order(match(df_tumor[,1],rots_noimp_tumor[,1])),]
  if(all(rots_noimp_tumor$Protein == df_tumor$Protein)){
    print("TRUE")
  } else{
    print("FALSE")
  }
  
  #stroma
  df_stroma <- filter(data, log2FoldChange < 0)
  rots_noimp_stroma <- filter(rots_noimp_prim, log2FoldChange < 0) 
  df_stroma <- filter(df_stroma, Protein %in% rots_noimp_stroma$Protein)
  rots_noimp_stroma <- filter(rots_noimp_stroma, Protein %in% df_stroma$Protein)
  
  df_stroma <- df_stroma[order(match(df_stroma[,1],rots_noimp_stroma[,1])),]
  if(all(rots_noimp_stroma$Protein == df_stroma$Protein)){
    print("TRUE")
  } else{
    print("FALSE")
  }
  cor <- c(cor(rots_noimp_tumor$pvalue, df_tumor$pvalue, method = "spearman"), 
           cor(rots_noimp_stroma$pvalue, df_stroma$pvalue, method = "spearman"))
}



rf_log2 <- corr_function_pvalue(rots_rf_log2_prim)
bpca_log2 <- corr_function_pvalue(rots_bpca_log2_prim)
null <- corr_function_pvalue(null_rots_prim)

corr_pvalue <- rbind(bpca_log2, rf_log2, null)
corr_pvalue <- as.data.frame(corr_pvalue, stringsAsFactors = F)



corr_pvalue$imputation <- c("BPCA", "RF", "null_data")

rownames(corr_pvalue) <- NULL

false_pos <- function(data){
  sign <- filter(data, pvalue < 0.05)
  sign_null <- filter(null_rots_prim, pvalue < 0.05)
  length(intersect(sign$Protein, sign_null$Protein))/nrow(sign)*100
}

noimp_falsp <- false_pos(rots_noimp_prim)
bpca_log2_falsp <- false_pos(rots_bpca_log2_prim)
rf_log2_prim <- false_pos(rots_rf_log2_prim)

corr_pvalue[,4] <- c(bpca_log2_falsp, rf_log2_prim, noimp_falsp)
corr_pvalue <- as.data.frame(corr_pvalue[,c(3,1,2,4)])

colnames(corr_pvalue) <- c("imputation","tumor", "stroma", "false_pos")

corr_pvalue
```


# Table for KEGG enrichment
```{r message=FALSE}
bpca_kegg <- read.delim("enrichment.KEGG_bpca_0.01.tsv", sep = "\t", header = T)

bpca_kegg <- bpca_kegg[order(bpca_kegg$false.discovery.rate),]

bpca_kegg <- as.data.frame(bpca_kegg[1:5, c(1:6,8)])
bpca_kegg$imputation <- "BPCA"


rf_kegg <- read.delim("enrichment.KEGG_rf_0.01.tsv", sep = "\t", header = T)

rf_kegg <- rf_kegg[order(rf_kegg$false.discovery.rate),]

rf_kegg <- as.data.frame(rf_kegg[1:5, c(1:6,8)])
rf_kegg$imputation <- "Random_Forest"


noimp_kegg <- read.delim("enrichment.KEGG_noimp_pvalue_0.01.tsv", sep = "\t", header = T)

noimp_kegg <- noimp_kegg[order(noimp_kegg$false.discovery.rate),]

noimp_kegg <- as.data.frame(noimp_kegg[, c(1:6,8)])

noimp_kegg$imputation <- "No_imputation"


combined_kegg <- rbind(noimp_kegg, bpca_kegg, rf_kegg)
combined_kegg <- as.data.frame(combined_kegg[,-1], stringsAsFactor = F)
combined_kegg <- as.data.frame(combined_kegg[,c(7,1:6)], stringsAsFactor = F)

combined_kegg
```

# linear regression table
```{r message=FALSE}
lm_imputation_prim <- function(data){
  #df <- filter(data, rownames(data) %in% rownames(pocroc_data_primary_regression))
  regression <- as.data.frame(t(data))
  if(all(rownames(regression) == rownames(coldata_final_primary))){
    regression$sample <- coldata_final_primary$strm_content
  } else{
    print("FALSE")
  }
  regression <- as.data.frame(regression[,c(dim(regression)[2], 1:dim(regression)[2] - 1)])
  lm_strm_content <- t(sapply(2:ncol(regression),function(j){
    fit <- lm(sample~regression[,j], data = regression)
    summary(fit)$coef[2,c(1:4)]
  } ) )
  
  lm_strm_content <- data.frame(lm_strm_content)
  colnames(lm_strm_content) <- c("Estimate", "std_error", "t_value", "pvalue")
  rownames(lm_strm_content) <- rownames(data)
  lm_strm_content$FDR <- p.adjust(lm_strm_content$pvalue, method = "BH")
  lm_strm_content <- lm_strm_content[order(lm_strm_content$pvalue),]
  lm_strm_content$rank <- 1:nrow(lm_strm_content)
  lm_strm_content <- rownames_to_column(lm_strm_content, "Protein")
  lm_strm_content
}


coldata_final_primary <- column_to_rownames(coldata_final_primary, "sample")

# no imputation - statistically linear with estimate in negative
lm_noimp <- lm_imputation_prim(pocroc_data_primary)
lm_bpca <- lm_imputation_prim(prot_bpca_5k_log2)
lm_rf <- lm_imputation_prim(prot_rf_5k_log2)

lm_noimp$imputation <- "noimp"
lm_bpca$imputation <- "BPCA"
lm_rf$imputation <- "RF"

combined <- rbind(filter(lm_noimp, Protein == "ACTBL_HUMAN"),
                  filter(lm_bpca, Protein == "ACTBL_HUMAN"),
                  filter(lm_rf, Protein == "ACTBL_HUMAN"),
                  filter(lm_noimp, Protein == "G3P_HUMAN"),
                  filter(lm_bpca, Protein == "G3P_HUMAN"),
                  filter(lm_rf, Protein == "G3P_HUMAN"),
                  filter(lm_noimp, Protein == "PAX8_HUMAN"),
                  filter(lm_bpca, Protein == "PAX8_HUMAN"),
                  filter(lm_rf, Protein == "PAX8_HUMAN"),
                  filter(lm_noimp, Protein == "MUC16_HUMAN"),
                  filter(lm_bpca, Protein == "MUC16_HUMAN"),
                  filter(lm_rf, Protein == "MUC16_HUMAN")) 

combined <- subset(combined, select = -c(rank, std_error, t_value))
combined
```

# volcano plots
```{r message=FALSE}
highlight_protein <- read.csv("highlight_proteins_DEPs.csv", stringsAsFactors = F)

# no impute
df <- separate(rots_noimp_prim, col = "Protein", into = c("Protein", "b"),
                                  sep = "_")
library(ggrepel)

ggplot(data = df, aes(x = log2FoldChange, y = -1*log10(pvalue))) + geom_point(size = 3, color = "grey") +
  geom_point(data = filter(df, log2FoldChange >= 0.5) %>% filter(., pvalue <= 0.01), color = "#e5f5f9", size = 4) +
  geom_point(data = filter(df, log2FoldChange <= -0.5) %>% filter(., pvalue <= 0.01), color = "#fee8c8", size = 4) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>%
               filter(., pvalue <= 0.01), color = "Blue", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>% 
                     filter(., pvalue <= 0.01), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange < -0.5) %>% 
               filter(., pvalue <= 0.01), color = "brown", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From)  %>% filter(., log2FoldChange < -0.5) %>%
                     filter(., pvalue <= 0.01), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  labs(y = "-log10 pvalue") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(size = 25))
  labs(title = "DEPs; Noimp imputation; primary samples N=5192; colored by p-value < 0.01") 


# BPCA impute
df <- separate(rots_bpca_log2_prim, col = "Protein", into = c("Protein", "b"),
                                  sep = "_")

ggplot(data = df, aes(x = log2FoldChange, y = -1*log10(pvalue))) + geom_point(size = 3, color = "grey") +
  geom_point(data = filter(df, log2FoldChange >= 0.5) %>% filter(., FDR <= 0.001), color = "#e5f5f9", size = 4) +
  geom_point(data = filter(df, log2FoldChange <= -0.5) %>% filter(., FDR <= 0.001), color = "#fee8c8", size = 4) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>%
               filter(., FDR <= 0.001), color = "Blue", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>% 
                     filter(., FDR <= 0.001), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange < -0.5) %>% 
               filter(., FDR <= 0.001), color = "brown", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From)  %>% filter(., log2FoldChange < -0.5) %>%
                     filter(., FDR <= 0.001), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  labs(y = "-log10 pvalue") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(size = 25)) +
  labs(title = "DEPs; BPCA imputation; primary samples N=5039; colored by FDR < 0.001") 

# Random Forest
df <- separate(rots_rf_log2_prim, col = "Protein", into = c("Protein", "b"),
                                  sep = "_")

ggplot(data = df, aes(x = log2FoldChange, y = -1*log10(pvalue))) + geom_point(size = 3, color = "grey") +
  geom_point(data = filter(df, log2FoldChange >= 0.5) %>% filter(., FDR <= 0.001), color = "#e5f5f9", size = 4) +
  geom_point(data = filter(df, log2FoldChange <= -0.5) %>% filter(., FDR <= 0.001), color = "#fee8c8", size = 4) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>%
               filter(., FDR <= 0.001), color = "Blue", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange > 0.5) %>% 
                     filter(., FDR <= 0.001), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  geom_point(data = filter(df, Protein %in% highlight_protein$From) %>% filter(., log2FoldChange < -0.5) %>% 
               filter(., FDR <= 0.001), color = "brown", size = 6) +
  geom_label_repel(data = filter(df, Protein %in% highlight_protein$From)  %>% filter(., log2FoldChange < -0.5) %>%
                     filter(., FDR <= 0.001), aes(label = Protein), nudge_x = -0.20, nudge_y = 0.05, size = 6) +
  labs(y = "-log10 pvalue") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(size = 25))
```

# individual proteins plot
```{r message=FALSE}
# plotting individual proteins
# actbl, gapdh, muc16, pax8
kelly.colours <- c("gray95", "gray13", "gold2", "plum4", "darkorange1", "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4", "lightpink2", "deepskyblue4", "lightsalmon2", 
                   "mediumpurple4", "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate", "gray19")
library(colorspace)
s9 <- sequential_hcl(9, "Reds", rev = T)

coldata_final_primary <- rownames_to_column(coldata_final_primary, "sample")

actbl <- function(data){
  df <- as.data.frame(t(filter(data, rownames(data) == "ACTBL_HUMAN")))
  df <- rownames_to_column(df, "sample")
  df <- df[order(match(df[,1],coldata_final_primary[,1])),]
  df$sample <- coldata_final_primary$sample
  if(all(df$sample == coldata_final_primary$sample)){
    df$strm_content <- coldata_final_primary$strm_content
  }else{
    print("FALSE")
  }
  df
}

gapdh <- function(data){
  df <- as.data.frame(t(filter(data, rownames(data) == "G3P_HUMAN")))
  df <- rownames_to_column(df, "sample")
  df <- df[order(match(df[,1],coldata_final_primary[,1])),]
  df$sample <- coldata_final_primary$sample
  if(all(df$sample == coldata_final_primary$sample)){
    df$strm_content <- coldata_final_primary$strm_content
  }else{
    print("FALSE")
  }
  df
}

pax8 <- function(data){
  df <- as.data.frame(t(filter(data, rownames(data) == "PAX8_HUMAN")))
  df <- rownames_to_column(df, "sample")
  df <- df[order(match(df[,1],coldata_final_primary[,1])),]
  df$sample <- coldata_final_primary$sample
  if(all(df$sample == coldata_final_primary$sample)){
    df$strm_content <- coldata_final_primary$strm_content
  }else{
    print("FALSE")
  }
  df
}

muc16 <- function(data){
  df <- as.data.frame(t(filter(data, rownames(data) == "MUC16_HUMAN")))
  df <- rownames_to_column(df, "sample")
  df <- df[order(match(df[,1],coldata_final_primary[,1])),]
  df$sample <- coldata_final_primary$sample
  if(all(df$sample == coldata_final_primary$sample)){
    df$strm_content <- coldata_final_primary$strm_content
  }else{
    print("FALSE")
  }
  df
}

# actbl
actbl_noimp <- actbl(pocroc_data_primary)
actbl_bpca_log2 <- actbl(prot_bpca_5k_log2)
actbl_rf <- actbl(prot_rf_5k_log2)


all(actbl_noimp$sample == actbl_bpca_log2$sample)
all(actbl_noimp$sample == actbl_rf$sample)

actbl_comb <- as.data.frame(cbind(actbl_noimp$ACTBL_HUMAN, actbl_bpca_log2$ACTBL_HUMAN,
                                  actbl_rf$ACTBL_HUMAN))
colnames(actbl_comb) <- c("noimp", "bpca_log2", "Random_Forest")
actbl_comb$sample <- actbl_noimp$sample
actbl_comb$strm_content <- actbl_noimp$strm_content


# gapdh
g3p_noimp <- gapdh(pocroc_data_primary)
g3p_bpca_log2 <- gapdh(prot_bpca_5k_log2)
g3p_rf <- gapdh(prot_rf_5k_log2)


all(g3p_noimp$sample == g3p_bpca_log2$sample)
all(g3p_noimp$sample == g3p_rf$sample)
g3p_comb <- as.data.frame(cbind(g3p_noimp$G3P_HUMAN, g3p_bpca_log2$G3P_HUMAN,
                                g3p_rf$G3P_HUMAN))
colnames(g3p_comb) <- c("noimp", "bpca_log2", "Random_Forest")
g3p_comb$sample <- g3p_noimp$sample
g3p_comb$strm_content <- g3p_noimp$strm_content


# pax8
pax8_noimp <- pax8(pocroc_data_primary)
pax8_bpca_log2 <- pax8(prot_bpca_5k_log2)
pax8_rf <- pax8(prot_rf_5k_log2)

all(pax8_noimp$sample == pax8_bpca_log2$sample)
all(pax8_noimp$sample == pax8_rf$sample)
pax8_comb <- as.data.frame(cbind(pax8_noimp$PAX8_HUMAN, pax8_bpca_log2$PAX8_HUMAN,
                                 pax8_rf$PAX8_HUMAN))
colnames(pax8_comb) <- c("noimp", "bpca_log2", "Random_forest")
pax8_comb$sample <- pax8_noimp$sample
pax8_comb$strm_content <- pax8_noimp$strm_content

# muc16
muc16_noimp <- muc16(pocroc_data_primary)
muc16_bpca_log2 <- muc16(prot_bpca_5k_log2)
muc16_rf <- muc16(prot_rf_5k_log2)

all(muc16_noimp$sample == muc16_bpca_log2$sample)
all(muc16_noimp$sample == muc16_rf$sample)
muc16_comb <- as.data.frame(cbind(muc16_noimp$MUC16_HUMAN,
                                  muc16_bpca_log2$MUC16_HUMAN,
                                  muc16_rf$MUC16_HUMAN))

colnames(muc16_comb) <- c("noimp", "bpca_log2",
                          "Random_Forest")
muc16_comb$sample <- muc16_bpca_log2$sample
muc16_comb$strm_content <- muc16_bpca_log2$strm_content


imp_prot <- cbind(actbl_comb, g3p_comb, pax8_comb, muc16_comb)
colnames(imp_prot)

imp_prot <- as.data.frame(imp_prot[,-c(9,10,14,15,19,20)])

colnames(imp_prot) <- c("noimp.actbl", "BPCA.actbl",
                        "RF.actbl",
                        "sample", "strm_content",
                        "noimp.g3p", "BPCA.g3p",
                        "RF.g3p",
                        "noimp.pax8", "BPCA.pax8", "RF.pax8",
                        "noimp.muc16", "BPCA.muc16", "RF.muc16")

imp_prot <- gather(imp_prot, key = "imputation", value = "intensity", -sample, -strm_content)
imp_prot <- separate(imp_prot, col = "imputation", into = c("imputation", "Protein"), sep = "\\.")

imp_prot$imputation[grep("noimp", imp_prot$imputation)] <- "None"
imp_prot$imputation[grep("RF", imp_prot$imputation)] <- "Random Forest"

imp_prot$imputation <- factor(imp_prot$imputation, levels = unique(imp_prot$imputation), ordered = TRUE)
imp_prot$strm_content <- factor(imp_prot$strm_content, levels = c("0", "50", "100"), ordered = TRUE)

imp_prot[is.na(imp_prot)] <- 0



plot_actin <- ggplot(data =  filter(imp_prot, Protein == "actbl"), aes(x = imputation, y = intensity, fill = strm_content)) +
  geom_boxplot() +
  scale_fill_manual(values = kelly.colours[2:8]) +
  theme_bw() +
  theme(text = element_text(size = 35)) +
  ggtitle("beta-Actin") +
  theme(legend.position = "none") +
  #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "") +
  ylab(expression(atop("Protein intensity", 
                       paste("(log2)"))))

plot_gapdh <- ggplot(data =  filter(imp_prot, Protein == "g3p"), aes(x = imputation, y = intensity, fill = strm_content)) +
  geom_boxplot() +
  scale_fill_manual(values = kelly.colours[2:8]) +
  theme_bw() +
  #scale_color_manual(values = c("#2ca25f", "#2c7fb8", "#756bb1", "black")) +
  theme(text = element_text(size = 35)) +
  ggtitle("GAPDH") +
  theme(legend.position = "none") +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "") +
  ylab(expression(atop("Protein intensity", 
                       paste("(log2)"))))

plot_muc16 <- ggplot(data =  filter(imp_prot, Protein == "muc16"), aes(x = imputation, y = intensity, fill = strm_content)) +
  geom_boxplot() +
  scale_fill_manual(values = kelly.colours[2:8]) +
  theme_bw() +
  #scale_color_manual(values = c("#2ca25f", "#2c7fb8", "#756bb1", "black")) +
  theme(text = element_text(size = 35)) +
  ggtitle("MUC16") +
  theme(legend.position = "none") +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "") +
  ylab(expression(atop("Protein intensity", 
                       paste("(log2)"))))



plot_pax8 <- ggplot(data =  filter(imp_prot, Protein == "pax8"), aes(x = imputation, y = intensity, fill = strm_content)) +
  geom_boxplot() +
  scale_fill_manual(values = kelly.colours[2:8]) +
  theme_bw() +
  #scale_color_manual(values = c("#2ca25f", "#2c7fb8", "#756bb1", "black")) +
  theme(text = element_text(size = 35),
        legend.position = "none") +
  ggtitle("PAX8") +
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "", fill = "Stromal content") +
  ylab(expression(atop("Protein intensity", 
                       paste("(log2)"))))

protein_grid <- cowplot::plot_grid(plot_actin, plot_gapdh, plot_muc16, plot_pax8)
protein_grid

```

# heatmaps for fragment missing values
```{r message=FALSE}

actbl <- read.csv("actbl_fragment_intensity.csv", stringsAsFactors = F)
gapdh <- read.csv("gapdh_fragment_intensity.csv", stringsAsFactors = F)
muc16 <- read.csv("muc16_fragment_intensity.csv", stringsAsFactors = F)
pax8 <-  read.csv("pax8_fragment_intensity.csv", stringsAsFactors = F)

coldata_final <- read.csv("coldata_final_103.csv", stringsAsFactors = F)


coldata_final <- as.data.frame(coldata_final, stringsAsFactors = F)

rownames(coldata_final) <- NULL

coldata_final <- column_to_rownames(coldata_final, "X")
coldata_final$TumorType[grep("Prim", coldata_final$TumorType)] <- "Primary"
coldata_final$TumorType[grep("PRIMAR", coldata_final$TumorType)] <- "Primary"

coldata_final$TumorType[grep("Recurr", coldata_final$TumorType)] <- "Recurrent"
coldata_final$TumorType[grep("RECURR", coldata_final$TumorType)] <- "Recurrent"

coldata_final$TumorType[grep("strm", coldata_final$phase)] <- "Stromal"
coldata_final$TumorType[grep("all", coldata_final$TumorType)] <- "pool"

coldata_final <- as.data.frame(coldata_final[-c(grep("pool", rownames(coldata_final))),])

coldata_final_primary <- filter(coldata_final, rownames(coldata_final) %in% samples_primary_paired_tum_strm$V1)

coldata_final_primary <- rownames_to_column(coldata_final_primary, "sample")
coldata_final_primary$sample <- paste(coldata_final_primary$sample, "1", sep = "_")

coldata_final_primary <- column_to_rownames(coldata_final_primary, "sample")

all(colnames(pax8[,4:44]) == rownames(coldata_final_primary))
pax8 <- column_to_rownames(pax8, "X")

test <- pax8

test[is.na(test)] <- 0

test <- test[apply(test == 0, 1, sum) >= 43, ]

pax8 <- filter(pax8, !rownames(pax8) %in% rownames(test))

peptide_pax8 <- subset(pax8, select = PeptideSequence)
pax8 <- subset(pax8, select = -c(PeptideSequence, ProteinName))



all(rownames(peptide_pax8) == rownames(pax8))

missing_percent <- as.data.frame(colSums(is.na(pax8)))
colnames(missing_percent) <- "Missing values count"
missing_percent$stroma <- "tumor"
missing_percent$stroma[grep("strm", rownames(missing_percent))] <- "stroma"
stroma_content <- subset(missing_percent, select = stroma)
missing_percent <- subset(missing_percent, select = -stroma)

colnames(stroma_content) <- "Tumor/stroma"

condition_colors <- list(PeptideSequence = kelly.colours[2:5])
condition_colors2 <- list(`Tumor/stroma` = kelly.colours[5:6])
names(condition_colors$PeptideSequence) <- unique(peptide_pax8$PeptideSequence)
names(condition_colors2$`Tumor/stroma`) <- unique(stroma_content$`Tumor/stroma`)


colAnn1 <- HeatmapAnnotation("Missing values count" = anno_barplot(missing_percent$`Missing values count`),
                             annotation_name_gp= gpar(fontsize = 15))


colAnn2 <- HeatmapAnnotation(df=stroma_content, which="column",
                             col = condition_colors2, annotation_name_gp= gpar(fontsize = 15),
                             annotation_legend_param = list(
                               `Tumor/stroma` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))

colAnn3 <- HeatmapAnnotation(df=peptide_pax8, which="row",
                             col = condition_colors, show_annotation_name = FALSE,
                             annotation_legend_param = list(
                               `PeptideSequence` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))




hmap <- Heatmap(
  pax8,
  name = "Fragment intensities",
  show_row_names = F,
  show_column_names = F,
  cluster_rows = F,
  cluster_columns = F,
  show_column_dend = TRUE,
  show_row_dend = F,
  row_dend_reorder = F,
  column_dend_reorder = F,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"), na_col = "grey",
  right_annotation = colAnn3, top_annotation = c(colAnn1, colAnn2),
  col = s9, column_title = "PAX8",
  heatmap_legend_param = list(
    title = "Fragment intensities",
    title_position = "lefttop-rot"))

draw(hmap, heatmap_legend_side="right", annotation_legend_side="right")


all(colnames(muc16[,4:44]) == rownames(coldata_final_primary))
muc16 <- column_to_rownames(muc16, "X")

# removing fragments not present in any samples (N = 25 fragments of 155 not quantified in all 41 samples)
test <- muc16

test[is.na(test)] <- 0

test <- test[apply(test == 0, 1, sum) >= 41, ]

muc16 <- filter(muc16, !rownames(muc16) %in% rownames(test))


peptide_muc16 <- subset(muc16, select = PeptideSequence)
muc16 <- subset(muc16, select = -c(PeptideSequence, ProteinName))

all(rownames(peptide_muc16) == rownames(muc16))

missing_percent <- as.data.frame(colSums(is.na(muc16)))
colnames(missing_percent) <- "Missing values count"
#missing_percent$stroma <- "tumor"
#missing_percent$stroma[grep("strm", rownames(missing_percent))] <- "stroma"
#stroma_content <- subset(missing_percent, select = stroma)
#missing_percent <- subset(missing_percent, select = -stroma)

condition_colors <- list(PeptideSequence = kelly.colours[2:5])
names(condition_colors$PeptideSequence) <- unique(peptide_pax8$PeptideSequence)

colAnn1 <- HeatmapAnnotation("Missing values count" = anno_barplot(missing_percent$`Missing values count`),
                             annotation_name_gp= gpar(fontsize = 20))

colAnn2 <- HeatmapAnnotation(df=stroma_content, which="column",
                             col = condition_colors2, annotation_name_gp= gpar(fontsize = 20),
                             annotation_legend_param = list(
                               `Tumor/stroma` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))

colAnn3 <- HeatmapAnnotation(df=peptide_muc16, which="row",
                             show_annotation_name = FALSE,
                             annotation_legend_param = list(
                               `PeptideSequence` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))

hmap <- Heatmap(
  muc16,
  name = "Fragment intensities",
  show_row_names = F,
  show_column_names = F,
  cluster_rows = F,
  cluster_columns = F,
  show_column_dend = TRUE,
  show_row_dend = F,
  row_dend_reorder = F,
  column_dend_reorder = F,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"), na_col = "grey",
  right_annotation = colAnn3, top_annotation = c(colAnn1, colAnn2),
  col = s9, column_title = "MUC16",
  heatmap_legend_param = list(
    title = "Fragment intensities",
    title_position = "lefttop-rot"))

draw(hmap, heatmap_legend_side="bottom", annotation_legend_side="bottom")


all(colnames(gapdh[,4:44]) == rownames(coldata_final_primary))
gapdh <- column_to_rownames(gapdh, "X")

# removing fragments not present in any samples (N = 8 fragments of 198 not quantified in all 41 samples)
test <- gapdh

test[is.na(test)] <- 0

test <- test[apply(test == 0, 1, sum) >= 41, ]

gapdh <- filter(gapdh, !rownames(gapdh) %in% rownames(test))

peptide_gapdh <- subset(gapdh, select = PeptideSequence)
gapdh <- subset(gapdh, select = -c(PeptideSequence, ProteinName))

all(rownames(peptide_gapdh) == rownames(gapdh))

missing_percent <- as.data.frame(colSums(is.na(gapdh)))
colnames(missing_percent) <- "Missing values count"


colAnn1 <- HeatmapAnnotation("Missing values count" = anno_barplot(missing_percent$`Missing values count`),
                             annotation_name_gp= gpar(fontsize = 20))

colAnn2 <- HeatmapAnnotation(df=stroma_content, which="column",
                             col = condition_colors2, annotation_name_gp= gpar(fontsize = 20),
                             annotation_legend_param = list(
                               `Tumor/stroma` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))

colAnn3 <- HeatmapAnnotation(df=peptide_gapdh, which="row",
                             show_annotation_name = FALSE,
                             annotation_legend_param = list(
                               `PeptideSequence` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))


hmap <- Heatmap(
  log2(gapdh),
  name = "Fragment intensities",
  show_row_names = F,
  show_column_names = F,
  cluster_rows = F,
  cluster_columns = F,
  show_column_dend = TRUE,
  show_row_dend = F,
  row_dend_reorder = F,
  column_dend_reorder = F,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"), na_col = "grey",
  right_annotation = colAnn3, top_annotation = c(colAnn1, colAnn2),
  col = s9, column_title = "GAPDH",
  heatmap_legend_param = list(
    title = "log2(Fragment intensities)",
    title_position = "lefttop-rot"))

draw(hmap, heatmap_legend_side="bottom", annotation_legend_side="bottom")

all(colnames(actbl[,4:44]) == rownames(coldata_final_primary))
actbl <- column_to_rownames(actbl, "X")

# removing fragments not present in any samples (none for actbl)
test <- actbl

test[is.na(test)] <- 0

test <- test[apply(test == 0, 1, sum) >= 41, ]

actbl <- filter(actbl, !rownames(actbl) %in% rownames(test))


peptide_actbl <- subset(actbl, select = PeptideSequence)
actbl <- subset(actbl, select = -c(PeptideSequence, ProteinName))

all(rownames(peptide_actbl) == rownames(actbl))

missing_percent <- as.data.frame(colSums(is.na(actbl)))
colnames(missing_percent) <- "Missing values count"

condition_colors <- list(PeptideSequence = kelly.colours[2:4])
names(condition_colors$PeptideSequence) <- unique(peptide_actbl$PeptideSequence)


colAnn1 <- HeatmapAnnotation("Missing values count" = anno_barplot(missing_percent$`Missing values count`),
                             annotation_name_gp= gpar(fontsize = 20))

colAnn2 <- HeatmapAnnotation(df=stroma_content, which="column",
                             col = condition_colors2, annotation_name_gp= gpar(fontsize = 20),
                             annotation_legend_param = list(
                               `Tumor/stroma` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))

colAnn3 <- HeatmapAnnotation(df=peptide_actbl, which="row",
                             show_annotation_name = FALSE,
                             col = condition_colors,
                             annotation_legend_param = list(
                               `PeptideSequence` = list(
                                 title_position = "lefttop-rot"
                               )
                             ))



hmap <- Heatmap(
  log2(actbl),
  name = "Fragment intensities",
  show_row_names = F,
  show_column_names = F,
  cluster_rows = F,
  cluster_columns = F,
  show_column_dend = TRUE,
  show_row_dend = F,
  row_dend_reorder = F,
  column_dend_reorder = F,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"), na_col = "grey",
  right_annotation = colAnn3, top_annotation = c(colAnn1, colAnn2),
  col = s9, column_title = "beta-Actin",
  heatmap_legend_param = list(
    title = "log2(Fragment intensities)",
    title_position = "lefttop-rot"))

draw(hmap, heatmap_legend_side="bottom", annotation_legend_side="bottom")




```

