---
title: "Imputation_Figure1"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries
```{r message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(imputeLCMD)
library(pcaMethods)
library(missForest)
library(ComplexHeatmap)
set.seed(4242)
library(hydroGOF)
library(ggcorrplot)
library(corrplot)
library(circlize)
library(RColorBrewer)
library(viridis)
library(readxl)
```


# figures for nonimputed data set
# Figure1.B heatmap
```{r}
prot_noimp <- read.csv("protein_quant_og_fragment_ms_noimp.csv")

prot_noimp <- as.data.frame(prot_noimp[-1,])
prot_noimp <- as.data.frame(prot_noimp[,-1])

# 2918 proteins with no imputation from the dilution experiment
rownames(prot_noimp) <- NULL

prot_noimp <- column_to_rownames(prot_noimp, "Protein")
prot_noimp[is.na(prot_noimp)] <- 0

# heatmap for the same replicate clustering
# metadata for heatmap
metadata_heatmap <- read.csv("metadata_heatmap.csv")
rownames(metadata_heatmap) <- metadata_heatmap$X

metadata_heatmap <- subset(metadata_heatmap, select = -c(X))

all(rownames(metadata_heatmap) == colnames(prot_noimp))

# getting the missing counts from fragment level
df <- read.table("og_fragment_ms_0.txt")
df <- as.data.frame(df[-1, -c(1:3)])

colnames(df) <- colnames(prot_noimp)
res <- colSums(df==0)/nrow(df)*100

#mean(res[1:3]) high mean missing values 
#mean(res[4:6]) low mean missing values 
#mean(res[7:9]) medium mean missing values 

metadata_heatmap$missing_fragment <- c(0, 16.52, 0, 0, 34.37, 0, 19.69, 0, 0)
missing_fragment <- as.data.frame(metadata_heatmap$missing_fragment)
colnames(missing_fragment) <- "percent_missing"
rownames(missing_fragment) <- rownames(metadata_heatmap)
metadata_heatmap <- subset(metadata_heatmap, select = -missing_fragment)
colnames(metadata_heatmap) <- "Sample Concentration"


kelly.colours <- c("gray95", "gray13", "gold2", "plum4", "darkorange1", "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4", "lightpink2", "deepskyblue4", "lightsalmon2", 
                   "mediumpurple4", "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate", "gray19")

condition_colors <- list(`Sample Concentration` = c("#313695", "#f6e8c3", "#f46d43"))
names(condition_colors$`Sample Concentration`) <- c("2ug", "4ug", "8ug")

colAnn <- HeatmapAnnotation(df=metadata_heatmap, which="col", 
                            col=condition_colors, annotation_width=unit(c(2, 8), "cm"), 
                            gap=unit(3, "mm"), annotation_name_gp= gpar(fontsize = 15),
                            annotation_legend_param = list(
                              `Sample Concentration` = list(
                                title_position = "lefttop-rot"
                              )
                            ))

colAnn2 <- HeatmapAnnotation("% missing values" = 
                               anno_barplot(missing_fragment$percent_missing),
                             annotation_name_gp= gpar(fontsize = 15))


hmap <- Heatmap(
  prot_noimp,
  #name = "Protein Intensity(log2)",
  show_row_names = FALSE,
  show_column_names = FALSE,
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_column_dend = TRUE,
  show_row_dend = FALSE,
  row_dend_reorder = TRUE,
  column_dend_reorder = TRUE,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"), top_annotation=c(colAnn, colAnn2),
  heatmap_legend_param = list(
    title = "Protein Intensity(log2)",
    title_position = "lefttop-rot"))

draw(hmap, heatmap_legend_side="right", annotation_legend_side="right")
```


# Figure 1.C
```{r}

cor_prot_noimp_data <- prot_noimp

cor_prot_noimp_data[is.na(cor_prot_noimp_data)] <- 0
cor_prot_noimp <- cor(cor_prot_noimp_data)
p.prot <- cor_pmat(cor_prot_noimp_data)


colfunc<-colorRampPalette(c("white", "yellow", "red"))

corrplot(cor_prot_noimp, type="upper", addrect = 3, rect.col = "red", tl.col="black", tl.srt=45,
         addCoef.col = "black",
         col = colfunc(150),
         p.mat = p.prot, sig.level = 0.001,
         cl.lim = c(0, 1), is.corr = FALSE,
         number.cex=1.65, tl.cex = 1.65)
```

# figure 1.D
```{r}

log_fold <- gather(prot_noimp[,c(1:3,7:9,4:6)], key = "Load_ug", value = "log2_Intensity")


log_fold$load <- "8ug"
log_fold$load[grep("Low_", log_fold$Load_ug)] <- "2ug"
log_fold$load[grep("Med", log_fold$Load_ug)] <- "4ug"


log_fold$Load_ug <- factor(log_fold$Load_ug, levels = rev(unique(log_fold$Load_ug)), ordered = TRUE)



ggplot(log_fold, aes(x = Load_ug, y = log2_Intensity, fill = load)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width = 0.1) +
  scale_fill_manual(values = c("#313695", "#f6e8c3", "#f46d43")) +
  labs(x = "Load input replicates", y = "log2(Protein_intensity)",
       fill = "Sample Concentration") +
  theme_bw() +
  theme(text = element_text(size = 35),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "bottom") +
  scale_y_continuous(breaks=seq(5, 18, 2))

```

# figure 1.E
```{r}
co.var.df <- function(x) (100*apply(x,1,sd)/rowMeans(x))

prot_noimp[prot_noimp == 0] <- NA

prot_noimp_raw <- prot_noimp

prot_noimp_raw <- 2^prot_noimp_raw

prot_noimp_raw[is.na(prot_noimp_raw)] <- 0

prot_noimp_raw$High_corr <- co.var.df(prot_noimp_raw[,c(1:3)])
prot_noimp_raw$med_corr <- co.var.df(prot_noimp_raw[,c(7:9)])
prot_noimp_raw$low_corr <- co.var.df(prot_noimp_raw[,c(4:6)])

prot_noimp_raw$all_corr <- co.var.df(prot_noimp_raw[,c(1:9)])

coeff_plot_noimp <- prot_noimp_raw[,c(10:13)]

coeff_plot_noimp <- gather(coeff_plot_noimp, key = "load", value = "Coeff_var")

coeff_plot_noimp$load_ug <- "8ug"

coeff_plot_noimp$load_ug[grep("low_", coeff_plot_noimp$load)] <- "2ug"
coeff_plot_noimp$load_ug[grep("med_", coeff_plot_noimp$load)] <- "4ug"
coeff_plot_noimp$load_ug[grep("all_", coeff_plot_noimp$load)] <- "all_loads"


coeff_plot_noimp <- filter(coeff_plot_noimp, !load == "all_corr")


coeff_plot_noimp$load <- factor(coeff_plot_noimp$load, levels = rev(unique(coeff_plot_noimp$load)), ordered = TRUE)

ggplot(coeff_plot_noimp, aes(x = load, y = Coeff_var, fill = load_ug)) +
  geom_violin() +
  scale_fill_manual(values = c("#313695", "#f6e8c3", "#f46d43")) +
  theme_bw() +
  theme(text = element_text(size = 35),
        legend.position = "bottom") +
  labs(x = "Load inputs for dilution series", y = "Coefficient of variance",
       fill = "Sample Concentration")
```


