---
title: "Suppl_figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# loading libraries
```{r message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(imputeLCMD)
library(pcaMethods)
library(missForest)
library(ComplexHeatmap)
set.seed(4242)
library(hydroGOF)
library(ggcorrplot)
library(corrplot)
library(circlize)
library(RColorBrewer)
library(viridis)
library(readxl)
```


# Supplimentary Figure 1.A
```{r message=FALSE}
comb_imp_foldchnge <- read.csv("comb_imp_foldchnge.csv")

comb_imp_foldchnge <- as.data.frame(comb_imp_foldchnge[,-1])

colnames(comb_imp_foldchnge) <- c("Random Forest", "LLS", "KNNmethod",
                                  "BPCA", "SVDmethod", "minProb", "minDet",
                                  "Zero", "None", "Ideal")

corr_foldchnge_imp <- cor(comb_imp_foldchnge)
p.imp <- cor_pmat(comb_imp_foldchnge)

corr_foldchnge_imp <- as.matrix(corr_foldchnge_imp)
p.foldchnge_imp <- cor_pmat(comb_imp_foldchnge)
col_cor_scale <- c('#f1eef6','#bdc9e1','#74a9cf','#0570b0')


corrplot(corr_foldchnge_imp, type="upper", addrect = 3, 
         rect.col = "red", tl.col="black", tl.srt=45,
         col = col_cor_scale,
         addCoef.col = "black",
         p.mat = p.foldchnge_imp, sig.level = 0.0001,
         cl.lim = c(-0.2, 1), is.corr = FALSE,
         number.cex=2, tl.cex = 2)
```

# Supplimentary Figure 1.C
```{r message=FALSE}
library(colorspace)

peptide <- read.csv("pept_gather.csv", stringsAsFactors = F)

peptide <- as.data.frame(peptide[,-1], stringsAsFactors = F)
colnames(peptide) <- c("load", "KNNmethod", "LLS", "Random Forest", "Ideal")

cor_pept <- cor(peptide[,c(2:5)])

p.pept <- cor_pmat(peptide[,c(2:5)])

oryel <- sequential_hcl(9, "YlOrRd", rev = T)

corrplot(cor_pept, type="upper", addrect = 3, rect.col = "red", tl.col="black", tl.srt=45,
         addCoef.col = "white",
         col = oryel,
         p.mat = p.pept, sig.level = 0.001,
         cl.lim = c(0.7, 1), is.corr = FALSE,
         number.cex=1.65, tl.cex = 1.65)
```

# Supplimentary Figure 1.D
```{r message=FALSE}
protein <- read.csv("prot_gather.csv", stringsAsFactors = F)

protein <- as.data.frame(protein[,-1], stringsAsFactors = F)
colnames(protein) <- c("load", "KNNmethod", "LLS", "Random Forest", "Ideal")

cor_prot <- cor(protein[,c(2:5)])

p.prot <- cor_pmat(protein[,c(2:5)])

oryel <- sequential_hcl(9, "YlOrRd", rev = T)

corrplot(cor_prot, type="upper", addrect = 3, rect.col = "red", tl.col="black", tl.srt=45,
         addCoef.col = "white",
         col = oryel,
         p.mat = p.prot, sig.level = 0.001,
         cl.lim = c(0.7, 1), is.corr = FALSE,
         number.cex=1.65, tl.cex = 1.65)
```

# Supplimentary Figure 1.E
```{r message=FALSE}

rsr_pept <- read.csv("rsr_pept_imp.csv")


label_pept <- rsr_pept$rsr
label_pept <- round(label_pept, digits = 2)

colnames(rsr_pept) <- c("X", "rsr", "Imputation")

rsr_pept$Imputation <- c("Ideal", "KNNmethod", "LLS", "Random Forest")

ggplot(rsr_pept, aes(x = Imputation, y = rsr, fill = Imputation)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("black", '#a65628','#f781bf','#999999')) +
  theme_bw() +
  labs(x = "Imputation Methods", y = "RMSE/SD") +
  geom_text(aes(label=label_pept), position=position_dodge(width=0.9), vjust=-0.25,
            size = 14) +
  theme(text = element_text(size = 40),
        axis.text.x = element_blank()) 

```

# Supplimentary Figure 1.F
```{r message=FALSE}
rsr_prot <- read.csv("rsr_prot_imp.csv")


label_prot <- rsr_prot$rsr
label_prot <- round(label_prot, digits = 2)

colnames(rsr_prot) <- c("X", "rsr", "Imputation")

rsr_prot$Imputation <- c("Ideal", "KNNmethod", "LLS", "Random Forest")

ggplot(rsr_prot, aes(x = Imputation, y = rsr, fill = Imputation)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("black", '#a65628','#f781bf','#999999')) +
  theme_bw() +
  labs(x = "Imputation Methods", y = "RMSE/SD") +
  geom_text(aes(label=label_prot), position=position_dodge(width=0.9), vjust=-0.25,
            size = 14) +
  theme(text = element_text(size = 40),
        axis.text.x = element_blank())
```

# Supplimentary Figure 2A-G
```{r message=FALSE}
protein_quant_minDet_pocroc <- read.csv("protein_quant_pocroc_norm_minDet.csv")

protein_quant_knn_pocroc <- read.csv("protein_quant_pocroc_norm_knn.csv")

protein_quant_minProb_pocroc <- read.csv("protein_quant_pilot_minProb.csv")

protein_quant_svd_pocroc <- read.csv("protein_quant_pilot_svd.csv")

protein_quant_bpca_pocroc <- read.csv("protein_quant_pilot_bpca.csv")

protein_quant_norm_noimp <- read.csv("protein_quant_norm_noimp.csv")

protein_quant_lls_pocroc <- read.csv("protein_quant_pilot_lls.csv")

protein_quant_rf_pocroc <- read.csv("protein_quant_pilot_rf_log2.csv")

protein_quant_norm_noimp <- as.data.frame(protein_quant_norm_noimp[-1,-1])

rownames(protein_quant_norm_noimp) <- NULL
protein_quant_norm_noimp <- column_to_rownames(protein_quant_norm_noimp, "Protein")



protein_quant_minDet_pocroc <- as.data.frame(protein_quant_minDet_pocroc[-1,-1])
protein_quant_knn_pocroc <- as.data.frame(protein_quant_knn_pocroc[-1,-1])
protein_quant_rf_pocroc <- as.data.frame(protein_quant_rf_pocroc[-1,-1])
protein_quant_minProb_pocroc <- as.data.frame(protein_quant_minProb_pocroc[-1,-1])
protein_quant_svd_pocroc <- as.data.frame(protein_quant_svd_pocroc[-1,-1])
protein_quant_bpca_pocroc <- as.data.frame(protein_quant_bpca_pocroc[-1,-1])
protein_quant_lls_pocroc <- as.data.frame(protein_quant_lls_pocroc[-1,-1])

all(colnames(protein_quant_lls_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_bpca_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_knn_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_minDet_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_minProb_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_svd_pocroc) == colnames(protein_quant_rf_pocroc))
all(colnames(protein_quant_svd_pocroc) == colnames(protein_quant_rf_pocroc))

protein_quant_norm_noimp <- protein_quant_norm_noimp[,c(1,3,2,5,4,8,10,9,7,6,12,11,14,13)]

column_names <- colnames(protein_quant_bpca_pocroc)
column_names <- sub('.', '', column_names[-1]) 

phase <- colnames(protein_quant_norm_noimp)

phase <- substr(phase, start = 1, stop = 4)

column_names <- c("Protein", paste(phase, column_names, sep = ""))

colnames(protein_quant_lls_pocroc) <- column_names
colnames(protein_quant_knn_pocroc) <- column_names
colnames(protein_quant_minDet_pocroc) <- column_names
colnames(protein_quant_rf_pocroc) <- column_names
colnames(protein_quant_minProb_pocroc) <- column_names
colnames(protein_quant_svd_pocroc) <- column_names
colnames(protein_quant_bpca_pocroc) <- column_names

protein_quant_lls_pocroc <- na.omit(protein_quant_lls_pocroc)


common_protein <- intersect(rownames(protein_quant_norm_noimp), protein_quant_bpca_pocroc$Protein)
common_protein <- intersect(common_protein, protein_quant_minProb_pocroc$Protein)
common_protein <- intersect(common_protein, protein_quant_lls_pocroc$Protein)


protein_quant_norm_noimp <- filter(protein_quant_norm_noimp, rownames(protein_quant_norm_noimp) %in% common_protein)
protein_quant_minDet_pocroc <- filter(protein_quant_minDet_pocroc, Protein %in% common_protein)
protein_quant_minProb_pocroc <- filter(protein_quant_minProb_pocroc, Protein %in% common_protein)
protein_quant_svd_pocroc <- filter(protein_quant_svd_pocroc, Protein %in% common_protein)
protein_quant_bpca_pocroc <- filter(protein_quant_bpca_pocroc, Protein %in% common_protein)
protein_quant_knn_pocroc <- filter(protein_quant_knn_pocroc, Protein %in% common_protein)
protein_quant_rf_pocroc <- filter(protein_quant_rf_pocroc, Protein %in% common_protein)
protein_quant_lls_pocroc <- filter(protein_quant_lls_pocroc, Protein %in% common_protein)

protein_quant_norm_noimp[is.na(protein_quant_norm_noimp)] <- 0

protein_quant_norm_noimp <- rownames_to_column(protein_quant_norm_noimp, "Protein")

cor_noimp_pocroc <- as.data.frame(cor(protein_quant_norm_noimp[,c(2:15)]))
cor_minDet_pocroc <- as.data.frame(cor(protein_quant_minDet_pocroc[,c(2:15)]))
cor_knn_pocroc <- as.data.frame(cor(protein_quant_knn_pocroc[,c(2:15)]))
cor_rf_pocroc <- as.data.frame(cor(protein_quant_rf_pocroc[,c(2:15)]))
cor_minProb_pocroc <- as.data.frame(cor(protein_quant_minProb_pocroc[,c(2:15)]))
cor_svd_pocroc <- as.data.frame(cor(protein_quant_svd_pocroc[,c(2:15)]))
cor_bpca_pocroc <- as.data.frame(cor(protein_quant_bpca_pocroc[,c(2:15)]))
cor_lls_pocroc <- as.data.frame(cor(protein_quant_lls_pocroc[,c(2:15)]))


all(colnames(cor_noimp_pocroc) == colnames(cor_minDet_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_knn_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_rf_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_minProb_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_svd_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_bpca_pocroc))
all(colnames(cor_noimp_pocroc) == colnames(cor_lls_pocroc))

colnames(cor_noimp_pocroc) <- c("1_1", "1_2", "1_3", "2_1", "2_2",
                                "3_1", "3_2", "3_3", "4_1", "4_2",
                                "5_1", "5_2", "6_1", "6_2")
rownames(cor_noimp_pocroc) <- c("1_1", "1_2", "1_3", "2_1", "2_2",
                                "3_1", "3_2", "3_3", "4_1", "4_2",
                                "5_1", "5_2", "6_1", "6_2")

colnames(cor_minDet_pocroc) <- colnames(cor_noimp_pocroc)
colnames(cor_knn_pocroc)<- colnames(cor_noimp_pocroc)
colnames(cor_rf_pocroc)<- colnames(cor_noimp_pocroc)
colnames(cor_minProb_pocroc)<- colnames(cor_noimp_pocroc)
colnames(cor_svd_pocroc)<- colnames(cor_noimp_pocroc)
colnames(cor_bpca_pocroc)<- colnames(cor_noimp_pocroc)
colnames(cor_lls_pocroc)<- colnames(cor_noimp_pocroc)

rownames(cor_minDet_pocroc) <- colnames(cor_noimp_pocroc)
rownames(cor_knn_pocroc)<- colnames(cor_noimp_pocroc)
rownames(cor_rf_pocroc)<- colnames(cor_noimp_pocroc)
rownames(cor_minProb_pocroc)<- colnames(cor_noimp_pocroc)
rownames(cor_svd_pocroc)<- colnames(cor_noimp_pocroc)
rownames(cor_bpca_pocroc)<- colnames(cor_noimp_pocroc)
rownames(cor_lls_pocroc)<- colnames(cor_noimp_pocroc)

s9 <- sequential_hcl(9, "Reds", rev = T)

hmap <- Heatmap(
  cor_noimp_pocroc,
  name = "Pearson's Correlation Coefficient",
  show_row_names = T,
  show_column_names = T,
  cluster_rows = T,
  cluster_columns = T,
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  row_dend_reorder = TRUE,
  column_dend_reorder = TRUE,
  clustering_method_rows = "ward.D2",
  clustering_method_columns = "ward.D2",
  width = unit(100, "mm"),
  col = s9,
  column_names_gp = gpar(fontsize = 25),
  row_names_gp = gpar(fontsize = 25),
  heatmap_legend_param = list(
    title = "Pearson's correlation coefficient",
    title_position = "leftcenter-rot"))

draw(hmap, heatmap_legend_side="left")

```
